name: Deploy API Documentation

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2023-12-14T12%3A35%3A26.107000Z@time-machines-npm.sealsecurity.io/
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: |
            package-lock.json
          node-version: '18'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run compile

      - name: Build Docs
        run: npm run docs
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Deploy Documentation 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
